'use client'

import { useCallback, useRef } from 'react'

interface UseInteractionOptions {
  /** Called on double-click (desktop) or double-tap (mobile) */
  onOpen: () => void
  /** Called on single click/tap (optional — e.g. for selection feedback) */
  onTap?: () => void
  /** Disable all interactions */
  disabled?: boolean
  /** Max interval (ms) between two taps to count as double-tap. Default: 300 */
  doubleTapInterval?: number
}

interface InteractionHandlers {
  onClick: (e: React.MouseEvent) => void
  onTouchEnd: (e: React.TouchEvent) => void
  onKeyDown: (e: React.KeyboardEvent) => void
}

/**
 * Unified interaction hook that provides:
 * - Desktop: double-click to open (native onDoubleClick is unreliable with touch)
 * - Mobile: double-tap to open (within configurable interval)
 * - Keyboard: Enter/Space to open
 * - No accidental single-tap opens on mobile
 *
 * Uses refs internally — zero re-renders from interaction tracking.
 */
export function useInteraction(options: UseInteractionOptions): {
  handlers: InteractionHandlers
  isActive: React.RefObject<boolean>
} {
  const {
    onOpen,
    onTap,
    disabled = false,
    doubleTapInterval = 300,
  } = options

  // Track last tap/click timestamp (ref = no re-render)
  const lastTapTimeRef = useRef(0)
  // Track whether touch was used (to distinguish touch-vs-mouse)
  const isTouchDeviceRef = useRef(false)
  // Active/pressed state (exposed as ref so parent can read it without re-render)
  const isActive = useRef(false)
  // Guard against touch+click double-fire
  const touchHandledRef = useRef(false)

  const handleDoubleTap = useCallback(() => {
    if (disabled) return
    onOpen()
  }, [disabled, onOpen])

  const processTap = useCallback(() => {
    if (disabled) return

    const now = Date.now()
    const elapsed = now - lastTapTimeRef.current

    if (elapsed < doubleTapInterval && elapsed > 0) {
      // Double tap detected
      lastTapTimeRef.current = 0
      handleDoubleTap()
    } else {
      // First tap — record time, trigger optional onTap feedback
      lastTapTimeRef.current = now
      onTap?.()
    }
  }, [disabled, doubleTapInterval, handleDoubleTap, onTap])

  const onClick = useCallback(
    (e: React.MouseEvent) => {
      if (disabled) return

      // If this click was generated by a touch event, skip it
      // (we already handled it in onTouchEnd)
      if (touchHandledRef.current) {
        touchHandledRef.current = false
        return
      }

      processTap()
    },
    [disabled, processTap]
  )

  const onTouchEnd = useCallback(
    (e: React.TouchEvent) => {
      if (disabled) return

      isTouchDeviceRef.current = true
      // Mark that we handled this touch so the synthetic click is ignored
      touchHandledRef.current = true

      // Reset the flag after a short delay (click fires ~300ms after touch)
      setTimeout(() => {
        touchHandledRef.current = false
      }, 400)

      processTap()
    },
    [disabled, processTap]
  )

  const onKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (disabled) return
      if (e.key === 'Enter' || e.key === ' ') {
        e.preventDefault()
        onOpen()
      }
    },
    [disabled, onOpen]
  )

  return {
    handlers: { onClick, onTouchEnd, onKeyDown },
    isActive,
  }
}
